# docker-compose.yml
version: '3.8' # You can remove this line too, as it's obsolete

services:
  app1:
    build: ./app1
    container_name: app1_container
    restart: always
    networks:
      - my_reverse_proxy_network

  app2:
    build: ./app2
    container_name: app2_container
    restart: always
    networks:
      - my_reverse_proxy_network

  nginx:
    image: nginx:latest # <--- Directly specify the image here
    container_name: nginx_reverse_proxy
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app1
      - app2
    networks:
      - my_reverse_proxy_network

networks:
  my_reverse_proxy_network:
    driver: bridge