name: Install Python 3.11+ on EC2 via Self-Hosted Runner

on:
  workflow_dispatch:

jobs:
  install-python-311:
    runs-on: self-hosted
    steps:
      - name: Update apt and install prerequisites
        run: |
          sudo apt-get update -y
          sudo apt-get install -y software-properties-common curl

      - name: Add deadsnakes PPA and install Python 3.11
        run: |
          sudo add-apt-repository ppa:deadsnakes/ppa -y
          sudo apt-get update -y
          sudo apt-get install -y python3.11 python3.11-venv python3.11-distutils python3.11-dev

      - name: Set Python 3.11 as default python3
        run: |
          sudo update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.11 2
          sudo update-alternatives --set python3 /usr/bin/python3.11

      - name: Install pip for Python 3.11
        run: |
          curl -sS https://bootstrap.pypa.io/get-pip.py | sudo python3.11

      - name: Verify Python and pip installation
        run: |
          python3 --version
          pip3 --version
