name: My First GitHub Actions

on: [push]

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Update apt
        run: sudo apt update

      - name: Install Python 3.10
        run: |
          sudo apt install -y software-properties-common
          sudo add-apt-repository ppa:deadsnakes/ppa -y
          sudo apt update
          sudo apt install -y python3.10 python3.10-venv python3.10-distutils

      - name: Verify Python Installation
        run: python3.10 --version
    
      - name: Run tests
        run: |
          cd src
           python -m pytest addition.py
