name: My First GitHub Actions

on: [push]

jobs:
  build:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v5

    - name: Install Python 3.11 (no sudo)
      run: |
        apt-get update -y
        apt-get install -y software-properties-common curl
        add-apt-repository -y ppa:deadsnakes/ppa
        apt-get update -y
        apt-get install -y python3.11 python3.11-venv python3.11-distutils
        update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.11 2
        update-alternatives --set python3 /usr/bin/python3.11
        curl -sS https://bootstrap.pypa.io/get-pip.py | python3.11

    - name: Install dependencies
      run: |
        python3 --version
        python3 -m pip install --upgrade pip
        pip3 install pytest

    - name: Run tests
      run: |
        cd src
        python3 -m pytest addition.py
